export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "on-tertiary": "#36301a",
        "on-primary-fixed": "#3a0a00",
        "background": "#131313",
        "error": "#ffb4ab",
        "surface-tint": "#ffb59e",
        "on-error": "#690005",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#eee2c1",
        "on-surface": "#e5e2e1",
        "outline-variant": "#5c4038",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#d1c6a6",
        "tertiary-container": "#9a9074",
        "surface-container-lowest": "#0e0e0e",
        "on-primary": "#5e1700",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "primary": "#ffb59e",
        "secondary-fixed-dim": "#ffb779",
        "tertiary": "#d1c6a6",
        "on-tertiary-fixed-variant": "#4e462e",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#2e1500",
        "outline": "#ac897f",
        "secondary-fixed": "#ffdcc1",
        "on-tertiary-container": "#2f2914",
        "inverse-primary": "#ae3200",
        "on-primary-fixed-variant": "#852400",
        "on-secondary": "#4c2700",
        "on-primary-container": "#531300",
        "secondary-container": "#a05800",
        "on-secondary-fixed-variant": "#6c3a00",
        "on-secondary-container": "#ffe8d8",
        "secondary": "#ffb779",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "primary-fixed-dim": "#ffb59e",
        "primary-fixed": "#ffdbd0",
        "error-container": "#93000a",
        "surface-container-highest": "#353534",
        "on-tertiary-fixed": "#211b07",
        "on-surface-variant": "#e5beb3",
        "inverse-surface": "#e5e2e1",
        "primary-container": "#ff571b",
        "surface-dim": "#131313"
      },
      "fontFamily": {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}

